### POST Request to /
curl -X POST -H "Content-Type: multipart/form-data" -F "bg=@/Users/parth/Documents/personal-git/watermark-services/watermark-service/test/testdata/test-bg.png" -F "logo=@/Users/parth/Documents/personal-git/watermark-services/watermark-service/test/testdata/test-logo.png"  -F outname=finale.png http://localhost:8080/ --output finale.png

